apiVersion: v1
kind: Pod
metadata:
  name: go-continuous-fuzz-runner
  namespace: default
spec:
  serviceAccountName: go-continuous-fuzz-sa
  containers:
    - name: runner
      image: go-continuous-fuzz
      imagePullPolicy: Never  
      volumeMounts:
        - name: config
          mountPath: /root/.go-continuous-fuzz/go-continuous-fuzz.conf
          subPath: go-continuous-fuzz.conf
        - name: shared
          mountPath: /mnt/shared/project
  volumes:
    - name: config
      configMap:
        name: go-continuous-fuzz-config
    - name: shared
      persistentVolumeClaim:
        claimName: shared-storage
  restartPolicy: Never