apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  go-continuous-fuzz.conf: |
    [Application Options]
    logdir = "{{ .Values.project.logdir }}"

    [Project]
    project.workspace-path = "{{ .Values.project.workspacePath }}"
    project.src-repo = "{{ .Values.project.srcRepo }}"
    project.s3-bucket-name = "{{ .Values.project.s3BucketName }}"

    [Fuzz Options]
    fuzz.crash-repo = "{{ .Values.fuzz.crashRepo }}"
{{- range .Values.fuzz.pkgsPath }}
    fuzz.pkgs-path = "{{ . }}"
{{- end }}
    fuzz.sync-frequency = "{{ .Values.fuzz.syncFrequency }}"
    fuzz.corpus-minimize-interval = "{{ .Values.fuzz.corpusMinimizeInterval }}"
    fuzz.iterations = {{ .Values.fuzz.iterations }}
    fuzz.num-workers = {{ .Values.fuzz.numWorkers }}
    fuzz.in-cluster = {{ .Values.fuzz.inCluster }}
    fuzz.namespace = "{{ .Release.Namespace }}"