apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GITHUB_AUTH_TOKEN: {{ .Values.github.authToken | quote }}