apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  containers:
    - name: {{ .Values.pod.container.name }}
      image: {{ .Values.pod.container.image }}
      imagePullPolicy: {{ .Values.pod.container.imagePullPolicy }}
      envFrom:
        - secretRef:
            name: {{ .Values.aws.secretName }}
        - secretRef:
            name: {{ .Values.github.secretName }}
      volumeMounts:
        - name: config
          mountPath: /root/.go-continuous-fuzz/go-continuous-fuzz.conf
          subPath: go-continuous-fuzz.conf
        - name: shared
          mountPath: {{ .Values.project.workspacePath }}
  volumes:
    - name: config
      configMap:
        name: {{ .Values.configMap.name }}
    - name: shared
      persistentVolumeClaim:
        claimName: {{ .Values.pvc.name }}
  restartPolicy: Never